spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
    show-sql: false

app:
  jwt:
    secret: test-secret-key-MUST-be-long-enough-123456789
    expiration-millis: 3600000

  cloudinary:
    cloud-name: "test-cloud"
    api-key: "123456"
    api-secret: "secret-test"

logging:
  level:
    root: WARN
